### PR TITLE
Add operators

### PR DESCRIPTION
**Pull request by eerii**
Hey, thank you so much for creating this wonderful plugin. I am doing a dialogue-based game in bevy for a game jam and this is everything I could have asked for, since other yarn-spinner libraries I tried are not up to date. I noticed there was no support still for operations on variables (equality, comparison and math), so I went ahead and added them, I hope it is ok with you. I tried to follow the style of the other functions on `handle_known_default_functions`. Thank you again, your library is beyond awesome!

New functions added:

```
Number.EqualTo
Number.NotEqualTo
String.EqualTo
String.NotEqualTo
Bool.EqualTo
Bool.NotEqualTo
Number.GreaterThan
Number.LessThan
Number.GreaterThanOrEqualTo
Number.LessThanOrEqualTo
Bool.Or
Bool.And
Bool.Xor
Bool.Not
Number.Add
Number.Minus
Number.Multiply
Number.Divide
Number.Modulo
```

Now you can do:

```
<<if $var == "value">>
    <<set $num = $num + 10>>
<<elseif $num > 10>>
    The value of a*b is {$a * $b}
<<endif>>
```

### CODE REVIEW

**Comment by eerii** [comment]
Hmm there seems to be a bug where the value is working correctly if used like `{1 == 1}`, which prints `true`, but in an if clause it is as if it was false. I'm going to look into it.

Edit: Ok, found the bug. In JumpIfFalse it was jumping when the bool on the stack was true. Should work fine now.

**Comment by sanbox-irl** [comment]
This PR looks wonderful, and I'd love to merge it. The only issue that as of this PR being written, I hadn't added the MIT license to the repo yet. Are you okay with this work being in the repo under the MIT license? I just added it to main.

**Comment by eerii** [comment]
Of course! The MIT license is perfect.

**Comment by sanbox-irl** [comment]
merged -- thank you very much!

**Pull request merged**
